<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\Persistence\**" />
    <Compile Remove="Contracts\Services\**" />
    <Compile Remove="Messaging\**" />
    <EmbeddedResource Remove="Contracts\Persistence\**" />
    <EmbeddedResource Remove="Contracts\Services\**" />
    <EmbeddedResource Remove="Messaging\**" />
    <None Remove="Contracts\Persistence\**" />
    <None Remove="Contracts\Services\**" />
    <None Remove="Messaging\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\Chat\" />
    <Folder Include="Domain\User\" />
    <Folder Include="Domain\Room\" />
  </ItemGroup>

</Project>
