<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contracts\Persistence\" />
    <Folder Include="Contracts\Services\" />
    <Folder Include="Domain\Chat\" />
    <Folder Include="Domain\User\" />
    <Folder Include="Domain\Room\" />
    <Folder Include="Messaging\Enums\" />
    <Folder Include="Messaging\Responses\" />
    <Folder Include="Messaging\Requests\" />
  </ItemGroup>

</Project>
