<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\Persistence\**" />
    <Compile Remove="Contracts\Services\**" />
    <Compile Remove="Domain\Chat\**" />
    <Compile Remove="Domain\Room\**" />
    <Compile Remove="Domain\User\**" />
    <Compile Remove="Messaging\**" />
    <EmbeddedResource Remove="Contracts\Persistence\**" />
    <EmbeddedResource Remove="Contracts\Services\**" />
    <EmbeddedResource Remove="Domain\Chat\**" />
    <EmbeddedResource Remove="Domain\Room\**" />
    <EmbeddedResource Remove="Domain\User\**" />
    <EmbeddedResource Remove="Messaging\**" />
    <None Remove="Contracts\Persistence\**" />
    <None Remove="Contracts\Services\**" />
    <None Remove="Domain\Chat\**" />
    <None Remove="Domain\Room\**" />
    <None Remove="Domain\User\**" />
    <None Remove="Messaging\**" />
  </ItemGroup>

</Project>
