<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\GameEngine\" />
    <Folder Include="Application\Services\" />
    <Folder Include="Infrastructure\Networking\" />
    <Folder Include="Infrastructure\Persistence\Configuration\" />
    <Folder Include="Infrastructure\Persistence\Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>
